### PR TITLE
Vagrant support

### PR DESCRIPTION
**Pull request by patcon**
I haven't actually changed anything, but simply added a straight up port to vagrant. Not sure if you've built it lately, but it seems that quite a few modules have broken packages, since they're `ensure`d at a specific build that is now out of date. (And as far as I've learned, sysadmins don't tend to lock down to build numbers. The assumption seems to be that if it's in the apt repo, then it's good to go. "Pinning" is usually only done when there are specific conflicts that apt gets confused with or doesn't recognize.)

Was looking at the community modules, and they just seem to `ensure` "present":
https://github.com/puppetlabs/puppetlabs-mysql/blob/master/manifests/server.pp#L19

Speaking of community modules, I've prepped this branch for librarian-puppet support, which is essentially a package manager for puppet modules that resolves dependencies into a lockfile (kinda like composer, if you're following that is php land)

Thinking that I can start converting some of your custom puppet modules into leveraging the  popular community modules, which will hopefully remove lots of overhead and give you easy access to snazzy new features. Would you mind if we took that approach?

Anyhow, like I said, psyched to help out with this project :)

### CODE REVIEW

**Comment by patcon** [comment]
Oh hey, this isn't ready for a merge yet, unless you want to leave the community cookbook stuff or another PR. This one _is_ technically broken, but I think you'll find that the puppet run is broken without vagrant too.

**Comment by patcon** [comment]
Hm. We'll also need to do some port forwarding and stuff like that, which isn't done yet. But first, I might just convert all the `ensure`s to "present" so that the puppet run will complete

**Comment by pirog** [comment]
Yeah just keep whatever you change in your fork for now.

We initially had all the ensures set to "present" but we also wanted to try
to enforce specific version numbers to maintain parity with pantheon's
stack. Let's talk about the stability implications of having packages keep
updating as some of the other stuff may rely on specific versions. I think
i'd like to figure out a way to keep updating packages but maybe not to
major new releases until we have a time to get everything else ready for
them.

On Tue, Feb 19, 2013 at 12:00 AM, Patrick Connolly <notifications@github.com

> wrote:
> 
> Hm. We'll also need to do some port forwarding and stuff like that, which
> isn't done yet. But first, I might just convert all the ensures to
> "present" so that the puppet run will complete
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kalamuna/kalabox/pull/1#issuecomment-13761027.

## 

Cheers,

Mike Pirog
Scientist and Co-Founder
East Bay Development
www.eastbaywebshop.com

**Comment by patcon** [comment]
OK, sounds good. Perhaps we could talk to the pantheon guys? If they're not at the most recent versions (assuming they're running `apt-get upgrade` regularly, which I think is best-practice?), then they likely have things pinned in `/etc/apt/preferences.d/*`. Thinking maybe they could just share those preference files to save us from needing to be so vigilant.

My understanding is that, if it's just a matter of them running `apt-get upgrade`s a few weeks behind, then there might not be significant gain from us pinning, since it's about the smallest version bumps we could ever encounter as developers. Seems like it might be more trouble than its worth, since some apt repos don't keep old build versions hanging around, and so asking for a specific one (like we're doing) would fail any puppet runs via vagrant -- possibly big UX fail for users.

EDIT: Right now, the puppet run at least finishes if you follow the "Installation" instructions in the README. I'll work on VM config like port forwarding and shared dirs later in the week :)

**Comment by patcon** [comment]
Currently working at removing samba module and some of the networking stuff, since Vagrant handles networking and shared dirs.

**Comment by patcon** [comment]
OK, cool. Seem to be all working so far. Removed all of the network module and can now simply access the 3 default ui's through these urls on the host after spinning up:
- `php.kala/`: phpmyadmin
- `kala/`: kalabox phpinfo() page
- `grind.kala/`: webgrind interface

Curious how we might need to modify things to get xdebug working, but I've got it working just fine within the ariadne VM, so it shouldn't be much different with puppet+vagrant

I'll work at testing some of the pantheon talky-talk features later

**Comment by pirog** [comment]
we've got a 2.x branch of kalastack now that is vagrant driven

**Pull request closed without merging**
